const data = {
  products: [
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/nike-shirt.png',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas training shirt',
      slug: 'adidas-training-shirt',
      category: 'Shirts',
      image: '/images/adidas-shirt.jpg',
      price: 100,
      countInStock: 7,
      brand: 'Adidas',
      rating: 5,
      numReviews: 1,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: '/images/nike-pants.jpg',
      price: 140,
      countInStock: 40,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 9,
      description: 'high quality pants',
    },
    {
      name: 'Adidas fit pants',
      slug: 'adidas-fit-pants',
      category: 'Pants',
      image: '/images/adidas-pants.jpg',
      price: 90,
      countInStock: 2,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 75,
      description: 'high quality pants',
    },
  ],
};

export default data;
